# Description:
#
# This script loads a collection of word similarity benchmarks generated
# by HESML, whcih contain the raw similarity values for each word pair.
# Then, the script computes a consolidated table including the Pearson and
# Spearman correlation metrics together with the harmonic score of the
# former ones.
#
# References:
# ----------

# We clear all session variables

rm(list = ls())

# IMPORTANT: configuration of the input/output directories
# We define below the input directory for the input raw results
# in CSV file format, and the output directory for the
# final assembled tables in CSV file format.
# You must change these values in order to
# point to the proper directories in your hard drive.
# We also define below the name of the input raw CSV files
# containing the experimental results.

# The input and output directories below must end with '/' in
# Unix-like format to be compatible with Windows
# or Linux-based R distributions.

inputDir = "C:/Versiones_Git_Oficiales_HESML/HESML/HESML_Library/ReproducibleExperiments/Embeddings_vs_OntologyMeasures_paper/RawOutputFiles/"

outputDir = inputDir

# Input raw CSV files generated by the reproducible experiments detailed
# in the paper.

raw_MC28_file = "raw_similarity_values_MC28_dataset.csv"
raw_RG65_file = "raw_similarity_values_RG65_dataset.csv"
raw_PSfull_file = "raw_similarity_values_PSfull_dataset.csv"
raw_Agirre201_file = "raw_similarity_values_Agirre201_lowercase_dataset.csv"
raw_SimLex665_file = "raw_similarity_values_SimLex665_dataset.csv"
raw_MTurk771_file = "raw_similarity_values_MTurk771_dataset.csv"
raw_MTurk287_235_file = "raw_similarity_values_MTurk287-235_dataset.csv"
raw_WS353Rel_file = "raw_similarity_values_WS353Rel_dataset.csv"
raw_Rel122_file = "raw_similarity_values_Rel122_dataset.csv"
raw_WS353Full_file = "raw_similarity_values_WS353Full_dataset.csv"
raw_SimLex111_file = "raw_similarity_values_SimLex111_dataset.csv"
raw_SimLex222_file = "raw_similarity_values_SimLex222_dataset.csv"
raw_SimLex999_file = "raw_similarity_values_SimLex999_dataset.csv"
raw_SimVerb3500_file = "raw_similarity_values_SimVerb3500_dataset.csv"
raw_MEN_file = "raw_similarity_values_MEN_dataset.csv"
raw_YP130_file = "raw_similarity_values_YP130_dataset.csv"
raw_RareWords2034_file = "raw_similarity_values_RareWords2034_dataset.csv"
raw_RareWords1401_file = "raw_similarity_values_RareWords1401_dataset.csv"
raw_SCWS1994_file = "raw_similarity_values_SCWS1994_dataset.csv"

# We load the input raw results file

rawdata_MC28<-read.csv(paste(inputDir, sep = "", raw_MC28_file),dec = ".", sep = ';')
rawdata_RG65<-read.csv(paste(inputDir, sep = "", raw_RG65_file),dec = ".", sep = ';')
rawdata_PSfull<-read.csv(paste(inputDir, sep = "", raw_PSfull_file),dec = ".", sep = ';')
rawdata_Agirre201<-read.csv(paste(inputDir, sep = "", raw_Agirre201_file),dec = ".", sep = ';')
rawdata_SimLex665<-read.csv(paste(inputDir, sep = "", raw_SimLex665_file),dec = ".", sep = ';')
rawdata_MTurk771<-read.csv(paste(inputDir, sep = "", raw_MTurk771_file),dec = ".", sep = ';')
rawdata_MTurk287_235<-read.csv(paste(inputDir, sep = "", raw_MTurk287_235_file),dec = ".", sep = ';')
rawdata_WS353Rel<-read.csv(paste(inputDir, sep = "", raw_WS353Rel_file),dec = ".", sep = ';')
rawdata_Rel122<-read.csv(paste(inputDir, sep = "", raw_Rel122_file),dec = ".", sep = ';')
rawdata_WS353Full<-read.csv(paste(inputDir, sep = "", raw_WS353Full_file),dec = ".", sep = ';')
rawdata_SimLex111<-read.csv(paste(inputDir, sep = "", raw_SimLex111_file),dec = ".", sep = ';')
rawdata_SimLex222<-read.csv(paste(inputDir, sep = "", raw_SimLex222_file),dec = ".", sep = ';')
rawdata_SimLex999<-read.csv(paste(inputDir, sep = "", raw_SimLex999_file),dec = ".", sep = ';')
rawdata_SimVerb3500<-read.csv(paste(inputDir, sep = "", raw_SimVerb3500_file),dec = ".", sep = ';')
rawdata_MEN<-read.csv(paste(inputDir, sep = "", raw_MEN_file),dec = ".", sep = ';')
rawdata_YP130<-read.csv(paste(inputDir, sep = "", raw_YP130_file),dec = ".", sep = ';')
rawdata_RareWords2034<-read.csv(paste(inputDir, sep = "", raw_RareWords2034_file),dec = ".", sep = ';')
rawdata_RareWords1401<-read.csv(paste(inputDir, sep = "", raw_RareWords1401_file),dec = ".", sep = ';')
rawdata_SCWS1994<-read.csv(paste(inputDir, sep = "", raw_SCWS1994_file),dec = ".", sep = ';')

# IMPORTANT: you must install the 'BioPhysConnectoR' package before to run the next three lines of code
# We sort the tables in descending order by using the row-based Average values (last column)

library(BioPhysConnectoR)

# ---------------------------------------------------------------------
# Table 1: Pearson correlation of all measures and embeddings in
# the nine datasets evaluated both by the ontoloy-based measures based
# on Wordnet as the pre-trained word emebedding models.
# ---------------------------------------------------------------------

table1<-matrix(nrow = 21, ncol = 9)

colnames(table1)<-c("MC28", "RG65", "PSfull", "Agirre201", "SimLex665", "MTurk771", "MTurk287/235", "WS353Rel", "Rel122");
rownames(table1)<- colnames(rawdata_MC28)[3:23]

# We define all datasets represented in table 1

rawdataAllDatasets = list(rawdata_MC28, rawdata_RG65, rawdata_PSfull, rawdata_Agirre201, rawdata_SimLex665, rawdata_MTurk771, rawdata_MTurk287_235, rawdata_WS353Rel, rawdata_Rel122)

nMeasures = nrow(table1)
nDatasets = length(rawdataAllDatasets)

for (iDataset in 1:nDatasets)
{
	# We get the raw data of the next dataset

	rawdata = rawdataAllDatasets[[iDataset]]

	# We evaluate the Pearson correlation value for each measure in the current dataset

	for (iMeasure in 1:nMeasures)
	{
		table1[iMeasure, iDataset] = cor(rawdata[,2], rawdata[, iMeasure + 2], method = "pearson")
	}
}

# We compute the average of the rows and add it as last column

table1 = cbind(table1, Avg = rowMeans(table1[,1:ncol(table1)]))
table1 = mat.sort(table1, ncol(table1), decreasing = TRUE)

# We save all the final assembled data tables 

write.csv(table1, file = paste(outputDir, sep="","table1.csv"))

