# Description:
#
# This script splits and merges the raw tables of results generated by the
# reproducibles experiments in order to reproduce the results in the
# report [1] below:
#
# References:
# ----------
# [1] Lastra-D?az, J. J., & Garc?a-Serrano, A. (2016).
# A refinement of the well-founded Information Content models with a
# very detailed experimental survey on WordNet (No. TR-2016-01).
# NLP and IR Research Group. ETSI Inform?tica. Universidad Nacional
# de Educaci?n a Distancia (UNED).
# http://e-spacio.uned.es/fez/view/bibliuned:DptoLSI-ETSI-Informes-Jlastra-refinement

# We clear all session variables

rm(list = ls())

# IMPORTANT: configuration of the input/output directories
# We define below the input directory for the input raw results
# in CSV file format, and the output directory for the
# final assembled tables in CSV file format.
# You must change these values in order to
# point to the proper directories in your hard drive.
# We also define below the name of the input raw CSV files
# containing the experimental results.

# The input and output directories below must end with '/' in
# Unix-like format to be compatible with Windows
# or Linux-based R distributions.
# First, we get the current file script directory

current_working_dir <- dirname(rstudioapi::getActiveDocumentContext()$path)

# and we set the working directory for the R project

setwd(current_working_dir)

# Define the root path 

inputDir = "../RawOutputFiles/"

# inputDir = "C:/Versiones_Oficiales_HESML/Full_Trunk_HESML/HESML/HESML_Library/ReproducibleExperiments/RawOutputFiles/"

outputDir = inputDir

# Input raw CSV files generated by the reproducible experiments detailed
# in the paper.

AI_table12_file = "AI_table12.csv"
AI_table15_16_RG65_file = "AI_table15_16_RG65.csv"
AI_table17_18_MC28_file = "AI_table17_18_MC28.csv"
AI_table19_20_Agirre201_file = "AI_table19_20_Agirre201.csv"
AI_table21_22_PS_file = "AI_table21_22_PS.csv"
AI_table23_24_SimLex665_file = "AI_table23_24_SimLex665.csv"

# We load the input raw results file

data_AI_table12<-read.csv(paste(inputDir, sep = "", AI_table12_file),dec = ".", sep = ';', skip = 1)
data_AI_table15_16_RG65<-read.csv(paste(inputDir, sep = "", AI_table15_16_RG65_file),dec = ".", sep = ';')
data_AI_table17_18_MC28<-read.csv(paste(inputDir, sep = "", AI_table17_18_MC28_file),dec = ".", sep = ';')
data_AI_table19_20_Agirre201<-read.csv(paste(inputDir, sep = "", AI_table19_20_Agirre201_file),dec = ".", sep = ';')
data_AI_table21_22_PS<-read.csv(paste(inputDir, sep = "", AI_table21_22_PS_file),dec = ".", sep = ';')
data_AI_table23_24_SimLex665<-read.csv(paste(inputDir, sep = "", AI_table23_24_SimLex665_file),dec = ".", sep = ';')

# We split and merge the data table containing the Pearson and Spearman
# correlation values into two independent tables. One for the Pearson
# values and the other with the Spearman values, as shown in the
# paper [1] above. Firstly, we extracts the columns containing Pearson
# correlation values, and secondly, we do the same with the Spearman
# values.

final_data_AI_table_12 = data_AI_table12[,c(1,2,3,5,7,9,11,4,6,8,10,12)]

final_data_AI_table_15 = data_AI_table15_16_RG65[,c(1,2,4,6,8,10,12,14,16,18,20,22,24,26)]
final_data_AI_table_16 = data_AI_table15_16_RG65[,c(1,3,5,7,9,11,13,15,17,19,21,23,25,27)]

final_data_AI_table_17 = data_AI_table17_18_MC28[,c(1,2,4,6,8,10,12,14,16,18,20,22,24,26)]
final_data_AI_table_18 = data_AI_table17_18_MC28[,c(1,3,5,7,9,11,13,15,17,19,21,23,25,27)]

final_data_AI_table_19 = data_AI_table19_20_Agirre201[,c(1,2,4,6,8,10,12,14,16,18,20,22,24,26)]
final_data_AI_table_20 = data_AI_table19_20_Agirre201[,c(1,3,5,7,9,11,13,15,17,19,21,23,25,27)]

final_data_AI_table_21 = data_AI_table21_22_PS[,c(1,2,4,6,8,10,12,14,16,18,20,22,24,26)]
final_data_AI_table_22 = data_AI_table21_22_PS[,c(1,3,5,7,9,11,13,15,17,19,21,23,25,27)]

final_data_AI_table_23 = data_AI_table23_24_SimLex665[,c(1,2,4,6,8,10,12,14,16,18,20,22,24,26)]
final_data_AI_table_24 = data_AI_table23_24_SimLex665[,c(1,3,5,7,9,11,13,15,17,19,21,23,25,27)]

# We compute the last average columns in table 12

final_data_AI_table_12 = cbind(final_data_AI_table_12, Avg_r = rowMeans(final_data_AI_table_12[,3:7]), Avg_rho =rowMeans(final_data_AI_table_12[,8:12]))

final_data_AI_table_12 = cbind(final_data_AI_table_12, Both = rowMeans(final_data_AI_table_12[,13:14]))

# We compute the average tables 10 (Pearson) and 11 (Spearman) shown in paper [1] above.
# First, it is necessary to extract the numerical columns 2 to 14 in order to compute the average,
# then we inserts the first columun with the namkes of the IC models.

final_data_AI_table_10 = cbind(IC_models = final_data_AI_table_15[,1], 0.2 * (final_data_AI_table_15[,2:14] + final_data_AI_table_17[,2:14] + final_data_AI_table_19[,2:14] + final_data_AI_table_21[,2:14] + final_data_AI_table_23[,2:14]))

final_data_AI_table_11 = cbind(IC_models = final_data_AI_table_16[,1], 0.2 * (final_data_AI_table_16[,2:14] + final_data_AI_table_18[,2:14] + final_data_AI_table_20[,2:14] + final_data_AI_table_22[,2:14] + final_data_AI_table_24[,2:14]))

# We save the matrix 'final_data_AI_table_11' above in order to
# compute the p-values between the IC models later.

matrix_AI_table_11 = final_data_AI_table_11

# We compute the average of the row in tables 10 and 11 and add it as last column

final_data_AI_table_10 = cbind(final_data_AI_table_10, Avg = rowMeans(final_data_AI_table_10[,2:14]))
final_data_AI_table_11 = cbind(final_data_AI_table_11, Avg = rowMeans(final_data_AI_table_11[,2:14]))

# IMPORTANT: you must install the 'BioPhysConnectoR' package before to run the next three lines of code
# We sort the tables 10 and 11 in descending order by using the row-based Average values (last column)

library(BioPhysConnectoR)

final_data_AI_table_10 = mat.sort(final_data_AI_table_10, 15, decreasing = TRUE)
final_data_AI_table_11 = mat.sort(final_data_AI_table_11, 15, decreasing = TRUE)

# We round the results to 4 decimals in order to reproduce the tables in the paper [1] exactly

final_data_AI_table_10 = format(final_data_AI_table_10, digits = 4)
final_data_AI_table_11 = format(final_data_AI_table_11, digits = 4)
final_data_AI_table_12 = format(final_data_AI_table_12, digits = 4)
final_data_AI_table_15 = format(final_data_AI_table_15, digits = 4)
final_data_AI_table_16 = format(final_data_AI_table_16, digits = 4)
final_data_AI_table_17 = format(final_data_AI_table_17, digits = 4)
final_data_AI_table_18 = format(final_data_AI_table_18, digits = 4)
final_data_AI_table_19 = format(final_data_AI_table_19, digits = 4)
final_data_AI_table_20 = format(final_data_AI_table_20, digits = 4)
final_data_AI_table_21 = format(final_data_AI_table_21, digits = 4)
final_data_AI_table_22 = format(final_data_AI_table_22, digits = 4)
final_data_AI_table_23 = format(final_data_AI_table_23, digits = 4)
final_data_AI_table_24 = format(final_data_AI_table_24, digits = 4)
final_data_AI_table_24 = format(final_data_AI_table_24, digits = 4)

# We save all the final assembled data tables in order to
# match the assembled tables in the paper [1] exactly.
# The coulmns in the output CSV files are separated by ','

write.csv(final_data_AI_table_10, file = paste(outputDir, sep="","AI_final_table_10.csv"))
write.csv(final_data_AI_table_11, file = paste(outputDir, sep="","AI_final_table_11.csv"))
write.csv(final_data_AI_table_12, file = paste(outputDir, sep="","AI_final_table_12.csv"))
write.csv(final_data_AI_table_15, file = paste(outputDir, sep="","AI_final_table_15.csv"))
write.csv(final_data_AI_table_16, file = paste(outputDir, sep="","AI_final_table_16.csv"))
write.csv(final_data_AI_table_17, file = paste(outputDir, sep="","AI_final_table_17.csv"))
write.csv(final_data_AI_table_18, file = paste(outputDir, sep="","AI_final_table_18.csv"))
write.csv(final_data_AI_table_19, file = paste(outputDir, sep="","AI_final_table_19.csv"))
write.csv(final_data_AI_table_20, file = paste(outputDir, sep="","AI_final_table_20.csv"))
write.csv(final_data_AI_table_21, file = paste(outputDir, sep="","AI_final_table_21.csv"))
write.csv(final_data_AI_table_22, file = paste(outputDir, sep="","AI_final_table_22.csv"))
write.csv(final_data_AI_table_23, file = paste(outputDir, sep="","AI_final_table_23.csv"))
write.csv(final_data_AI_table_24, file = paste(outputDir, sep="","AI_final_table_24.csv"))


# Function: matrix.Pvalues
#
# This function computes a matrix of pairwise p-values between
# a set of methods defined by row vectors. This function is
# used to compute the p-values matrices shown in figures 25 and
# 26 of the report [1] above.

matrix.Pvalues<-function(rowBasedMatrixMethods, rowNames)
{
	# We get the dimensions of the matrix

	nrows = nrow(rowBasedMatrixMethods)
	ncols = ncol(rowBasedMatrixMethods)

	# We create a blank square matrix to store the pairwise
	# p-values between two paired rows (metrod samples)
	
	outputMatrix = matrix(nrow=nrows,ncol=nrows)

	# We compute the p-values between pairwise methods

	for (i in 1:(nrows - 1))
	{
		for (j in (i + 1):nrows)
		{
			outputMatrix[i,j] = t.test(x = as.numeric(matrix(rowBasedMatrixMethods[i,1:ncols])), y = as.numeric(matrix(rowBasedMatrixMethods[j,1:ncols])), alternative = "two.sided", mu = 0, paired = TRUE, conf.level = 0.95)$p.value * 0.5
			outputMatrix[j,i] = outputMatrix[i,j]
		}
	}

	# We set the names of rows and columns

	colnames(outputMatrix) = rowNames
	rownames(outputMatrix) = rowNames

	# We return the output matrix

	return (outputMatrix)
}

# We compute the p-values matrix in table 25 with the pairwise
# valus between IC models

final_data_AI_table_25 = matrix.Pvalues(matrix_AI_table_11[,2:14], matrix_AI_table_11[,1])
final_data_AI_table_25 = round(final_data_AI_table_25, 3)

write.csv(final_data_AI_table_25, file = paste(outputDir, sep="","AI_final_table_25.csv"))

# We read the raw table 12 generated by HESMLclient
# and compute the p-values

final_data_AI_table_26 = matrix.Pvalues(final_data_AI_table_12[,8:12], final_data_AI_table_12[,1])
final_data_AI_table_26 = round(final_data_AI_table_26, 3)

write.csv(final_data_AI_table_26, file = paste(outputDir, sep="","AI_final_table_26.csv"))
