# Description:
#
# This script loads a collection of sentence similarity benchmarks generated
# by HESMLSTSclient program, which contain the raw similarity values for
# sentence pair. Then, the script computes a collection of consolidated tables
# including the Pearson, Spearman and harmonic score metrics.
#
# References:
# ----------

# We clear all session variables

rm(list = ls())

# IMPORTANT:configuration of the input/output directories
# We define below the input directory for the input raw results
# in CSV file format, and the output directory for the
# final assembled tables in CSV file format.
# You must change these values in order to
# point to the proper directories in your hard drive.
# We also define below the name of the input raw CSV files
# containing the experimental results.

# The input and output directories below must end with '/' in
# Unix-like format to be compatible with Windows
# or Linux-based R distributions.

# Define the root path 

# rootDir = "D:/Versiones_Dev_HESML/HESML_Library/ReproducibleExperiments/BioSentenceSimilarity_paper"
rootDir = "/home/alicia/Desktop/HESML/HESML_Library/ReproducibleExperiments/BioSentenceSimilarity_paper"

# We import the library that implements the data structures.

library(collections)

# We create an OrderedDict object with all the experiments that will be evaluated.

experiments <- OrderedDictL()

# We define the subdirectory experiment and the caption for showing the results in Latex and HTML format
# and we add to the dictionary all the String-based measures experiments

experimentSubdirectory = "BioSentenceSimFinalRawOutputFiles"
strCaption = paste("Table \\label{table:", experimentSubdirectory, "}: Pearson (r), Spearman ($\rho$) and Harmonic score (h) obtained by each unsupervised sentence similarity method evaluated herein.", sep="")

experiments$set(experimentSubdirectory, strCaption)

# We create a Dictionary object for printing the Latex tables with the captions

latexTables <- OrderedDict()

# Loop for the defined experiments and calculate the scores for Pearson, Sperman and Harmonic.

for(iExperimentSubdirectory in experiments$keys())
{
    # We get the experiment subdirectory and the caption for the Latex File

    iExperimentCaption <- experiments$get(iExperimentSubdirectory)

    # We define the output directory and the input datasets directories

    outputDir =  paste(rootDir, "/", iExperimentSubdirectory, "/", sep = "")

    inputDir = outputDir
    
    # Input raw CSV files generated by the reproducible experiments detailed
    # in the companion paper for each sentence similarity dataset
    
    # We load the input raw results file
    
    rawdata_BIOSSES <- read.csv(paste(inputDir, sep = "", "raw_similarity_BIOSSES.csv"), dec = ".", sep = ';')
    rawdata_MedSTS  <- read.csv(paste(inputDir, sep = "", "raw_similarity_MedSTSFull.csv"), dec = ".", sep = ';')
    rawdata_CTR     <- read.csv(paste(inputDir, sep = "", "raw_similarity_CTR.csv"), dec = ".", sep = ';')
    
    # mat.sort function is copied from source files of
    # BioPhysConnectoR package which is now unavailable.
    # Source code was retrieved from https://rdrr.io/cran/BioPhysConnectoR/src/R/mat.sort.r
    
    mat.sort<-function(mat,sort,decreasing=FALSE){
      m<-do.call("order",c(as.data.frame(mat[,sort]),decreasing=decreasing))
      mat[m,]
    }
    
    # ---------------------------------------------------------------------
    # Raw output file format:
    # Raw similarity files contain the similarity values returned by each
    # semantic measure for each sentence pair. 
    # First column contains the uman judgements for each sentence pair
    # whilst subsequent columns contain the values returned by the
    # sentence similaritu measures.
    # ---------------------------------------------------------------------
    
    # ---------------------------------------------------------------------
    # Table 1: Pearson and Spearman metrics of all sentence similarity
    # measures.
    # ---------------------------------------------------------------------
    
    # We define all datasets represented in table 1
    
    rawdata_allDatasets <- list(rawdata_BIOSSES, rawdata_MedSTS, rawdata_CTR)
    
    # We create a separated table for each metric by removing the first column
    # which contains the human judgements. Measures are arranged in rows
    # whilst datasets are arranged in columns.
    
    table_Pearson <- matrix(nrow = ncol(rawdata_BIOSSES) - 1,
                            ncol = length(rawdata_allDatasets),
                            dimnames = list(colnames(rawdata_BIOSSES)[2:ncol(rawdata_BIOSSES)],
                                            c("BIOSSES", "MedSTS", "CTR")))
    
    table_Spearman <- table_Pearson
    table_Harmonic <- table_Pearson
    
    # Loop for the computation of the metrics
    
    nMeasures <- nrow(table_Pearson)
    nDatasets <- length(rawdata_allDatasets)
    
    for (iDataset in 1:nDatasets)
    {
      # We get the raw data of the next dataset
      
      rawdata <- rawdata_allDatasets[[iDataset]]
      
      # We evaluate the Pearson and Spearman metrics for each measure in the current dataset
      
      for (iMeasure in 1:nMeasures)
      {
        rawdata[,1]
        rawdata[, iMeasure + 1]
        
        table_Pearson[iMeasure, iDataset] <- cor(rawdata[,1], rawdata[, iMeasure + 1], use="complete.obs", method = "pearson")
        table_Spearman[iMeasure, iDataset] <- cor(rawdata[,1], rawdata[, iMeasure + 1], use="complete.obs", method = "spearman")
        table_Harmonic[iMeasure, iDataset] <- 2 * table_Pearson[iMeasure, iDataset] * table_Spearman[iMeasure, iDataset] / (table_Pearson[iMeasure, iDataset] + table_Spearman[iMeasure, iDataset])
      }
    }
    
    # ------------------------------------------------------------
    # We merge all metrics (Pearson, Spearman and Harmonic score)
    # into a same data table by concatening previouos data tables.
    # ------------------------------------------------------------
    
    table_allMetrics <- cbind(table_Pearson, table_Spearman, table_Harmonic, Avg = rowMeans(table_Harmonic[1:nrow(table_Harmonic),]))
    
    table_allMetrics <- mat.sort(table_allMetrics, ncol(table_allMetrics), decreasing = TRUE)
    
    # We set the column names to the final matrix
    
    colnames(table_allMetrics) <- c("r", "r", "r",
                                    '$\\rho$', '$\\rho$', '$\\rho$',
                                    "h", "h", "h", 
                                    "Avg")
    
    # We reorder the matrix columns grouping by dataset names.
    
    table_allMetrics <- table_allMetrics[ , c(1,4,7,2,5,8,3,6,9,10) ]
    
    # We make a copy of the tables in order to round their values to 3 decimal digits
    
    table_allMetrics_rounded <- round(table_allMetrics, 3);
    
    table_allMetrics_rounded <- as.data.frame(table_allMetrics_rounded)
    table_allMetrics_rounded
    
    # We save all final assembled data tables 
    
    write.csv(table_allMetrics, file = paste(outputDir,"table_allMetrics.csv", sep=""))
    write.csv(table_allMetrics_rounded, file = paste(outputDir, "table_allMetrics_rounded.csv", sep=""))
    
    # We add the output table to the Latex dictionary
    
    latexTables$set(iExperimentCaption, table_allMetrics_rounded)
}



#-------------------------------
# LATEX report generation
# 
# IMPORTANT NOTE: To avoid the problem of oversizing the box, add manually the next command BEFORE tabular:
#
# \resizebox{\columnwidth}{!}{%
#
# TABLE DATA
#
# }
# \end{table}
#-------------------------------

library(knitr)
library(readr)
library(kableExtra)
library(stringr)
library(xtable)

# Define the string with all the concatenated tables

strLatexTables <- ""

# Loop for the tables created and print them in a latex file

for(iExperimentCaption in latexTables$keys())
{
  # We get the experiment subdirectory and the caption for the Latex File
  
  table_allMetrics_rounded <- latexTables$get(iExperimentCaption)
  
  # We define the latex table with the data
  
  table_latex <- xtable(table_allMetrics_rounded, type = "latex", digits=4, method = "compact")
  
  # We add extra rows to the table before printing it
  
  addtorow      <- list()
  addtorow$pos  <- list()
  
  # We add an extra header with the dataset groups
  
  addtorow$pos[[1]] <- -1
  addtorow$command  <- c('\\hline \\multicolumn{1}{c}{ } & \\multicolumn{3}{c}{BIOSSES} & \\multicolumn{3}{c}{MedSTS} & \\multicolumn{3}{c}{CTR} & \\multicolumn{1}{c}{Avg} \\\\ ')
  
  # We save the tables in latex and HTML format files. The HTML format is for 
  
  strLatexTables <- paste(strLatexTables, sep="\n\n", print(xtable(table_latex, caption = iExperimentCaption, digits=3), caption.placement = 'top',
                                                            add.to.row = addtorow, comment=FALSE, size="\\tiny", table.placement="!h", sanitize.colnames.function = identity))
}

# Write the Latex table in a file

write_file(strLatexTables, "table_allMetrics_experiment.tex")

# And open the table in the default file browser.

browseURL("table_allMetrics_experiment.tex")
