# Description:
#
# This script loads a collection of sentence similarity benchmarks generated
# by HESMLSTSclient program, which contain the raw similarity values for
# sentence pair. Then, the script create the tables for analyzing the results.
#

# We clear all session variables

rm(list = ls())

# We add the dplyr library

library(dplyr)

# Import the readr library

library(readr)

# IMPORTANT:configuration of the input/output directories
# We define below the input directory for the input raw results
# in CSV file format, and the output directory for the
# final assembled tables in CSV file format.
# You must change these values in order to
# point to the proper directories in your hard drive.
# We also define below the name of the input raw CSV files
# containing the experimental results.

# The input and output directories below must end with '/' in
# Unix-like format to be compatible with Windows
# or Linux-based R distributions.

# First, we get the current file script directory

current_working_dir <- dirname(rstudioapi::getActiveDocumentContext()$path)

# and we set the working directory for the R project

setwd(current_working_dir)

# Define the root path 

rootDir = "../BioSentenceSimilarity_paper"

# We define the subdirectory experiment and the caption for showing the results in Latex and HTML format
# and we add to the dictionary all the String-based measures experiments

experimentSubdirectory = "BioSentenceSimFinalRawOutputFiles"
preprocessedExperimentsSubdirectory = "BioSentenceSimFinalProcessedOutputFiles"

# We define the output directory 

dir.create(paste(rootDir, "/", preprocessedExperimentsSubdirectory, "/", sep = ""))
outputDir =  paste(rootDir, "/", preprocessedExperimentsSubdirectory, "/", sep = "")

# Input raw CSV files generated by the reproducible experiments detailed
# in the companion paper for each sentence similarity dataset

# We define the input datasets directories

inputDir = paste(rootDir, "/", experimentSubdirectory, "/", sep = "")

# We load the input raw results file for best combinations (FINAL RESULTS)

source(paste("bio_sentence_sim_scripts", "readBESTCOMBS.R", sep = "/"), local = knitr::knit_global())

# First, we select all the measures, and we will only work with a dataset. 

rawdata_results_medsts <- na.omit(rawdata_BESTCOMBS[3][[1]])

# Now, we read the file which contains the sentences 

path_to_medsts_sentences_file <- "../../SentenceSimDatasets/BIOSSESNormalized.tsv"

# Use read_tsv() to read text file

sentences = read_tsv(path_to_medsts_sentences_file, col_names = FALSE)

#################################################
#################################################

# Pre-processing the data

#################################################
#################################################

# We add a column with the normalized Human scores to [0,1] using si = (xi – min(x)) / (max(x) – min(x))

# First, we get the max and min values

max_human <- max(rawdata_results_medsts$Human)
min_human <- min(rawdata_results_medsts$Human)

rawdata_results_medsts$HumanNormalized <- with(rawdata_results_medsts, (Human - min_human) / (max_human - min_human) )

# We add, for each measure, the value that represents the error: normalized_absolute_relative_error(i) = |score_measure(i) - score_human_norm(i)| / score_human_norm(i)

for (i in colnames(rawdata_results_medsts))
{
  # We do not parse the columns Human and HumanNormalize
  
  if(i != "Human" & i != "HumanNormalized")
  {
    # First, we calculate the error for each row and we set a generic column name "colname_i"
    
    rawdata_results_medsts$colname_i <- with(rawdata_results_medsts, abs(rawdata_results_medsts[[i]] - HumanNormalized))
    
    # Then, we set the new column name. For instance, "abs_relative_error_"
    
    names(rawdata_results_medsts)[names(rawdata_results_medsts) == 'colname_i'] <- paste("abs_relative_error_", i, sep="")
    
    # We create another column with no absolute values
    
    rawdata_results_medsts$colname_j <- with(rawdata_results_medsts, rawdata_results_medsts[[i]] - HumanNormalized)
    
    # Then, we set the new column name. For instance, "relative_error_"
    
    names(rawdata_results_medsts)[names(rawdata_results_medsts) == 'colname_j'] <- paste("rel_error_", i, sep="")
  }
}

rawdata_results_biosses_filtered <- rawdata_results_medsts

#################################################
#################################################

# Analytics stage

#################################################
#################################################

# We plot the histograms

# LiBlock <- hist(rawdata_results_biosses_filtered$rel_error_LiBlock)

# We test if the data has a normal distribution

library("dplyr")
library("ggpubr")

# First, visually, using the Q-Q plot

ggqqplot(rawdata_results_biosses_filtered$rel_error_LiBlock)

# Second, we make the saphiro test

t <- shapiro.test(rawdata_results_biosses_filtered$rel_error_LiBlock)

is_normal_distribution = FALSE
if(t$p.value > 0.05)
  is_normal_distribution = TRUE

is_normal_distribution


# Get the density estimate
density_LiBlock=density(rawdata_results_biosses_filtered$rel_error_LiBlock)
plot(density_LiBlock$x,density_LiBlock$y,type="l", col=rgb(0,0,1), xlim=c(-1,1), main="Probability Density Function (DF) of the similarity error function",xlab="Similarity error = Estimated similarity value - Normalized human score",ylab="Frequency of error")

density_WBSM_AncSPLRada=density(rawdata_results_biosses_filtered$rel_error_WBSM_AncSPLRada)
lines(density_WBSM_AncSPLRada$x,density_WBSM_AncSPLRada$y,type="l", col=rgb(1,0,0))

density_bio_embedding_intrinsic=density(rawdata_results_biosses_filtered$rel_error_bio_embedding_intrinsic)
lines(density_bio_embedding_intrinsic$x,density_bio_embedding_intrinsic$y,type="l", col=rgb(0,1,0))

density_oubiobert=density(rawdata_results_biosses_filtered$rel_error_oubiobert.base.uncased_tok.wordpiecetokenizer_lc_sw.nonestopwords_cf.default_ner.none)
lines(density_oubiobert$x,density_oubiobert$y,type="l", col=rgb(0,1,1))

legend("topright", c("LiBlock (M4)", "WBSM_Rada (M7)", "BioWordVec_int (26)", "ouBioBERT (M47)"), col=c(rgb(0,0,1), rgb(1,0,0),rgb(0,1,0),rgb(0,1,1)), lwd=10)

