# Description:
#
# This script assemblies the table 4 as shown in paper [1]
# below, starting from the raw output files generated by the
# reproducible experiments introduced in [2].
#
# References:
# ----------
# [1] Lastra-Díaz, J. J., and García-Serrano, A. (2015).
# A novel family of IC-based similarity measures with a
# detailed experimental survey on WordNet. Engineering
# Applications of Artificial Intelligence Journal,46, 140–153.
#
# [2] Lastra-Díaz, J. J., and García-Serrano, A. (2016).
# HESML: a scalable ontology-based semantic similarity
# measures library with a set of reproducible experiments and
# a replication dataset.
# Submitted for publication to the
# Information Systems Journal.

# We clear all session variables

rm(list = ls())

# IMPORTANT: configuration of the input/output directories
# We define below the input directory for the input raw
# results in CSV file format, and the output directory for the
# final assembled tables in CSV file format.
# You must change these values in order to
# point to the proper directories in your hard drive.
# We also define below the name of the input raw CSV files
# containing the experimental results.

# The input and output directories below must end with '/' in
# Unix-like format to be compatible with Windows
# or Linux-based R distributions.

inputDir = "C:/Versiones_Oficiales_HESML/Full_Trunk_HESML/HESML/HESML_Library/ReproducibleExperiments/RawOutputFiles/"

outputDir = inputDir

# Input raw CSV files generated by the reproducible
# experiments detailed in the paper [2].

EAAI_table4_file = "EAAI_table4_nonICmeasures.csv"
EAAI_table5_PS_file = "EAAI_table5_PS.csv"
EAAI_table5_RG65_file = "EAAI_table5_RG65.csv"
EAAI_table6_RG65_file = "EAAI_table6_RG65.csv"
EAAI_table7_PS_file = "EAAI_table7_PS.csv"
EAAI_table8_PS_file = "EAAI_table8_PS.csv"
EAAI_table8_RG65_file = "EAAI_table8_RG65.csv"

# We load the input raw results file

data_EAAI_table4<-read.csv(paste(inputDir, sep = "", EAAI_table4_file), dec = ".", sep = ';', skip = 1)

data_EAAI_table5_PS<-read.csv(paste(inputDir, sep = "", EAAI_table5_PS_file), dec = ".", sep = ';')

data_EAAI_table5_RG65<-read.csv(paste(inputDir, sep = "", EAAI_table5_RG65_file), dec = ".", sep = ';')

data_EAAI_table6_RG65<-read.csv(paste(inputDir, sep = "", EAAI_table6_RG65_file), dec = ".", sep = ';')

data_EAAI_table7_PS<-read.csv(paste(inputDir, sep = "", EAAI_table7_PS_file), dec = ".", sep = ';')

data_EAAI_table8_PS<-read.csv(paste(inputDir, sep = "", EAAI_table8_PS_file), dec = ".", sep = ';')

data_EAAI_table8_RG65<-read.csv(paste(inputDir, sep = "", EAAI_table8_RG65_file), dec = ".", sep = ';')

# We fill the table 4 with the data from the non IC-based similarity measures

table4 = data_EAAI_table4[,3:8]
rownames(table4) = data_EAAI_table4[,1]

tab4_rownames = rownames(table4)

# We fill the data corresponding to the IC-based
# similarity measures

for (iSim in 2:13)
{
    icBasedRow = t(c(max(data_EAAI_table5_RG65[, iSim]),max(data_EAAI_table5_PS[, iSim]),max(data_EAAI_table6_RG65[, iSim]),max(data_EAAI_table7_PS[, iSim]),max(data_EAAI_table8_RG65[, iSim]),max(data_EAAI_table8_PS[, iSim])))
    colnames(icBasedRow) = colnames(table4)
    table4 <- rbind(table4, icBasedRow)
}

# We set all row names for the table 4

rownames(table4) <- c(tab4_rownames, colnames(data_EAAI_table5_RG65[,2:13]))

# We compute the average by rows on each dataset
# (last three columns of table 4 shown in the paper [1])

final_table4 = cbind(table4, Avg_RG65 = rowMeans(table4[,c(1,3,5)]))
final_table4 = cbind(final_table4, Avg_PS = rowMeans(table4[,c(2,4,6)]))
final_table4 = cbind(final_table4, Overall = rowMeans(table4))

# Finally, we sort the table 4 in descending order by using the values in the last column

library(BioPhysConnectoR)

final_table4 = mat.sort(final_table4, 9, decreasing = TRUE)

# We round the results to 4 decimals in order to reproduce the table 4 in the paper [1] exactly

final_table4 = round(final_table4, digits = 4)

# We save the final table 4 in CSv file format

write.csv(final_table4, file = paste(outputDir, sep="","EAAI_final_table_4.csv"))



